name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '55 */5 * * *' # This triggers the workflow every 5 hours and 55 minutes

jobs:
  trigger-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger deploy workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: deploy.yml
        token: ${{ secrets.GITHUB_TOKEN }}
